### ISSUE TITLE
Transfer jit-open/email-incident-notification-plugin into the Camunda Community Hub

### ISSUE THREAD

**Issue by MiguelitoEnrique** [camunda-community-hub/email-incident-notification-plugin#7]
As described in the instructions on https://github.com/camunda-community-hub/community I am creating this issue to transfer the repository to the Camunda Community Hub.

**Comment by celanthe** [comment]
Hi again @MiguelitoEnrique! Thank you so much for transferring this repository to the Camunda Community Hub. :)

As I mentioned in the other issue, If you would be so kind as to review the [extension lifecycle documentation](https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md) and determine where this extension is in its current lifecycle, that would be great! 

Once you've done that, you can feel free to add the corresponding Shields.io badge and a Community Extension badge to the extension's README. If you have any questions, please let me know. I am happy to help!
